/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.jkamcc.musicbrainz.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Artist service. Represents a row in the &quot;artist&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.jkamcc.musicbrainz.model.impl.ArtistModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.jkamcc.musicbrainz.model.impl.ArtistImpl}.
 * </p>
 *
 * @author Juan Carrillo
 * @see Artist
 * @see com.jkamcc.musicbrainz.model.impl.ArtistImpl
 * @see com.jkamcc.musicbrainz.model.impl.ArtistModelImpl
 * @generated
 */
public interface ArtistModel extends BaseModel<Artist> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a artist model instance should use the {@link Artist} interface instead.
	 */

	/**
	 * Returns the primary key of this artist.
	 *
	 * @return the primary key of this artist
	 */
	public Integer getPrimaryKey();

	/**
	 * Sets the primary key of this artist.
	 *
	 * @param primaryKey the primary key of this artist
	 */
	public void setPrimaryKey(Integer primaryKey);

	/**
	 * Returns the ID of this artist.
	 *
	 * @return the ID of this artist
	 */
	public Integer getId();

	/**
	 * Sets the ID of this artist.
	 *
	 * @param id the ID of this artist
	 */
	public void setId(Integer id);

	/**
	 * Returns the name of this artist.
	 *
	 * @return the name of this artist
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this artist.
	 *
	 * @param name the name of this artist
	 */
	public void setName(String name);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.jkamcc.musicbrainz.model.Artist artist);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.jkamcc.musicbrainz.model.Artist> toCacheModel();

	@Override
	public com.jkamcc.musicbrainz.model.Artist toEscapedModel();

	@Override
	public com.jkamcc.musicbrainz.model.Artist toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}