/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.jkamcc.musicbrainz.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the ArtistMeta service. Represents a row in the &quot;artist_meta&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.jkamcc.musicbrainz.model.impl.ArtistMetaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.jkamcc.musicbrainz.model.impl.ArtistMetaImpl}.
 * </p>
 *
 * @author Juan Carrillo
 * @see ArtistMeta
 * @see com.jkamcc.musicbrainz.model.impl.ArtistMetaImpl
 * @see com.jkamcc.musicbrainz.model.impl.ArtistMetaModelImpl
 * @generated
 */
public interface ArtistMetaModel extends BaseModel<ArtistMeta> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a artist meta model instance should use the {@link ArtistMeta} interface instead.
	 */

	/**
	 * Returns the primary key of this artist meta.
	 *
	 * @return the primary key of this artist meta
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this artist meta.
	 *
	 * @param primaryKey the primary key of this artist meta
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this artist meta.
	 *
	 * @return the ID of this artist meta
	 */
	public long getId();

	/**
	 * Sets the ID of this artist meta.
	 *
	 * @param id the ID of this artist meta
	 */
	public void setId(long id);

	/**
	 * Returns the rating of this artist meta.
	 *
	 * @return the rating of this artist meta
	 */
	public int getRating();

	/**
	 * Sets the rating of this artist meta.
	 *
	 * @param rating the rating of this artist meta
	 */
	public void setRating(int rating);

	/**
	 * Returns the rating count of this artist meta.
	 *
	 * @return the rating count of this artist meta
	 */
	public int getRatingCount();

	/**
	 * Sets the rating count of this artist meta.
	 *
	 * @param ratingCount the rating count of this artist meta
	 */
	public void setRatingCount(int ratingCount);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.jkamcc.musicbrainz.model.ArtistMeta artistMeta);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.jkamcc.musicbrainz.model.ArtistMeta> toCacheModel();

	@Override
	public com.jkamcc.musicbrainz.model.ArtistMeta toEscapedModel();

	@Override
	public com.jkamcc.musicbrainz.model.ArtistMeta toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}