/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.jkamcc.musicbrainz.model.impl;

import com.jkamcc.musicbrainz.model.Artist;
import com.jkamcc.musicbrainz.model.ArtistModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Artist service. Represents a row in the &quot;artist&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.jkamcc.musicbrainz.model.ArtistModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ArtistImpl}.
 * </p>
 *
 * @author Juan Carrillo
 * @see ArtistImpl
 * @see com.jkamcc.musicbrainz.model.Artist
 * @see com.jkamcc.musicbrainz.model.ArtistModel
 * @generated
 */
public class ArtistModelImpl extends BaseModelImpl<Artist>
	implements ArtistModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a artist model instance should use the {@link com.jkamcc.musicbrainz.model.Artist} interface instead.
	 */
	public static final String TABLE_NAME = "artist";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id", Types.INTEGER },
			{ "name", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table artist (id INTEGER not null primary key,name VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table artist";
	public static final String ORDER_BY_JPQL = " ORDER BY artist.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY artist.id ASC";
	public static final String DATA_SOURCE = "musicBrainzDataSource";
	public static final String SESSION_FACTORY = "musicBrainzSessionFactory";
	public static final String TX_MANAGER = "musicBrainzTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.jkamcc.musicbrainz.model.Artist"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.jkamcc.musicbrainz.model.Artist"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.jkamcc.musicbrainz.model.Artist"));

	public ArtistModelImpl() {
	}

	@Override
	public Integer getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(Integer primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Artist.class;
	}

	@Override
	public String getModelClassName() {
		return Artist.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("name", getName());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer id = (Integer)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}
	}

	@Override
	public Integer getId() {
		return _id;
	}

	@Override
	public void setId(Integer id) {
		_id = id;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@Override
	public Artist toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Artist)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ArtistImpl artistImpl = new ArtistImpl();

		artistImpl.setId(getId());
		artistImpl.setName(getName());

		artistImpl.resetOriginalValues();

		return artistImpl;
	}

	@Override
	public int compareTo(Artist artist) {
		Integer primaryKey = artist.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Artist)) {
			return false;
		}

		Artist artist = (Artist)obj;

		Integer primaryKey = artist.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<Artist> toCacheModel() {
		ArtistCacheModel artistCacheModel = new ArtistCacheModel();

		artistCacheModel.id = getId();

		artistCacheModel.name = getName();

		String name = artistCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			artistCacheModel.name = null;
		}

		return artistCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", name=");
		sb.append(getName());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("com.jkamcc.musicbrainz.model.Artist");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Artist.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] { Artist.class };
	private Integer _id;
	private String _name;
	private Artist _escapedModel;
}