/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.jkamcc.musicbrainz.model.impl;

import com.jkamcc.musicbrainz.model.ArtistMeta;
import com.jkamcc.musicbrainz.service.ArtistMetaLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the ArtistMeta service. Represents a row in the &quot;artist_meta&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ArtistMetaImpl}.
 * </p>
 *
 * @author Juan Carrillo
 * @see ArtistMetaImpl
 * @see com.jkamcc.musicbrainz.model.ArtistMeta
 * @generated
 */
public abstract class ArtistMetaBaseImpl extends ArtistMetaModelImpl
	implements ArtistMeta {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a artist meta model instance should use the {@link ArtistMeta} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			ArtistMetaLocalServiceUtil.addArtistMeta(this);
		}
		else {
			ArtistMetaLocalServiceUtil.updateArtistMeta(this);
		}
	}
}